# Generated by Django 3.0.3 on 2020-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('question', models.TextField(max_length=5000)),
                ('answer', models.CharField(max_length=350)),
                ('options', models.CharField(max_length=500)),
            ],
        ),
    ]
